//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtachFile
    {
        public int AtachFileID { get; set; }
        public byte[] FileData { get; set; }
        public string FileName { get; set; }
        public int FileSize { get; set; }
        public int LetterID { get; set; }
    
        public virtual Letters Letters { get; set; }
    }
}
