//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Letters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Letters()
        {
            this.AtachFile = new HashSet<AtachFile>();
            this.Refrences = new HashSet<Refrences>();
            this.SendLetter = new HashSet<SendLetter>();
        }
    
        public int LetterID { get; set; }
        public string Subject { get; set; }
        public string Abstract { get; set; }
        public string Maintext { get; set; }
        public string LetterNum { get; set; }
        public string CreateDate { get; set; }
        public int UserID { get; set; }
        public byte SecuretyType { get; set; }
        public byte ForceType { get; set; }
        public byte BayganiType { get; set; }
        public byte PeygiriType { get; set; }
        public byte AttachmentType { get; set; }
        public byte LetterType { get; set; }
        public byte DraftyType { get; set; }
        public byte AnswerType { get; set; }
        public string Answerdeadline { get; set; }
        public string Refrence { get; set; }
        public int ReplayLetterID { get; set; }
        public string SendLetterDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtachFile> AtachFile { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Refrences> Refrences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SendLetter> SendLetter { get; set; }
    }
}
