//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refrences
    {
        public int RefrenceID { get; set; }
        public int UserID { get; set; }
        public int LetterID { get; set; }
        public int RefrenceUserID { get; set; }
        public int ReciveRefrenceUserID { get; set; }
        public string CreateDate { get; set; }
    
        public virtual Letters Letters { get; set; }
        public virtual Users Users { get; set; }
    }
}
