//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendLetter
    {
        public int SendLetterID { get; set; }
        public int LetterID { get; set; }
        public int UserID { get; set; }
        public Nullable<byte> ReadType { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Letters Letters { get; set; }
        public virtual Users Users { get; set; }
    }
}
