//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SenNote
    {
        public int SendNoteID { get; set; }
        public int NoteID { get; set; }
        public int UserID { get; set; }
    
        public virtual Note Note { get; set; }
        public virtual Users Users { get; set; }
    }
}
