//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersJobs
    {
        public int UsersJobsID { get; set; }
        public int UserID { get; set; }
        public int JobsID { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public byte Status { get; set; }
    
        public virtual Jobs Jobs { get; set; }
        public virtual Users Users { get; set; }
    }
}
