//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_LetterWhitSignutre
    {
        public int LetterID { get; set; }
        public string Subject { get; set; }
        public string Abstract { get; set; }
        public string Maintext { get; set; }
        public string LetterNum { get; set; }
        public string CreateDate { get; set; }
        public int UserID { get; set; }
        public byte SecuretyType { get; set; }
        public byte ForceType { get; set; }
        public byte BayganiType { get; set; }
        public byte PeygiriType { get; set; }
        public byte AttachmentType { get; set; }
        public byte LetterType { get; set; }
        public byte DraftyType { get; set; }
        public byte AnswerType { get; set; }
        public string Answerdeadline { get; set; }
        public string Refrence { get; set; }
        public int ReplayLetterID { get; set; }
        public string FarsiSecuretyType { get; set; }
        public string FarsiForceType { get; set; }
        public string FarsiBayganiType { get; set; }
        public string FarsiPeygiriType { get; set; }
        public string FarsiAttachmentType { get; set; }
        public string FarsiLetterType { get; set; }
        public string FarsiDraftyType { get; set; }
        public string FarsiAnswerType { get; set; }
        public string FullName { get; set; }
        public string UserFirstName { get; set; }
        public string UserFamily { get; set; }
        public string SendLetterDate { get; set; }
        public byte[] UserSignutre { get; set; }
    }
}
