//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_RefrenceT
    {
        public int rojoshodeid { get; set; }
        public string rojoshodeName { get; set; }
        public string erjakonandeName { get; set; }
        public int RefrenceID { get; set; }
        public int erjadahandeid { get; set; }
        public int erjashodeid { get; set; }
        public int LetterID { get; set; }
        public string Subject { get; set; }
        public string Abstract { get; set; }
        public string Maintext { get; set; }
        public string erjashodename { get; set; }
        public string LetterNum { get; set; }
        public string FarsiSecuretyType { get; set; }
        public string FarsiForceType { get; set; }
        public string FarsiBayganiType { get; set; }
        public string FarsiPeygiriType { get; set; }
        public string FarsiLetterType { get; set; }
        public string CreateDate { get; set; }
        public int ReciveRefrenceUserID { get; set; }
    }
}
