//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ReciveNote
    {
        public string Subject { get; set; }
        public string MainText { get; set; }
        public int UserID_Sender { get; set; }
        public int SendNoteID { get; set; }
        public int UserID_reciver { get; set; }
        public string User_Reciver { get; set; }
        public string User_Sender { get; set; }
        public int NoteID { get; set; }
        public string CrateDate { get; set; }
    }
}
