//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Remembers
    {
        public int RememberID { get; set; }
        public string Subject { get; set; }
        public string Text { get; set; }
        public string CreateDate { get; set; }
        public string RememberDate { get; set; }
        public string FarsiIsRead { get; set; }
        public int UserID { get; set; }
        public byte IsRead { get; set; }
    }
}
