//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_RefUser
    {
        public string UserFamily { get; set; }
        public string UserFirstName { get; set; }
        public int RefrenceID { get; set; }
        public int UserID { get; set; }
        public int RefrenceUserID { get; set; }
        public int LetterID { get; set; }
        public string Subject { get; set; }
        public string Abstract { get; set; }
        public string Maintext { get; set; }
        public int ReciveRefrenceUserID { get; set; }
        public string UserRefrenceshode { get; set; }
        public string Expr3 { get; set; }
        public int Expr5 { get; set; }
        public int Expr6 { get; set; }
        public string Expr9 { get; set; }
        public string Expr10 { get; set; }
        public string Expr8 { get; set; }
        public int Expr11 { get; set; }
        public int Expr12 { get; set; }
        public int Expr7 { get; set; }
        public int Expr13 { get; set; }
    }
}
