//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Users
    {
        public int UserID { get; set; }
        public string UserFirstName { get; set; }
        public string UserFamily { get; set; }
        public string UserUserName { get; set; }
        public string UserPassword { get; set; }
        public string UserPersonalCode { get; set; }
        public string FarsiGender { get; set; }
        public string FarsiUserActivity { get; set; }
        public string UserEmail { get; set; }
        public string UserTell { get; set; }
        public byte[] UserImage { get; set; }
        public string UserCreateDate { get; set; }
        public byte[] UserSignutre { get; set; }
        public string UserBrithDay { get; set; }
        public byte UserGender { get; set; }
        public byte UserActivity { get; set; }
    }
}
