//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_UserLog
    {
        public string UserFirstName { get; set; }
        public string UserFamily { get; set; }
        public string UserFullName { get; set; }
        public string ComputerName { get; set; }
        public string EnterDateTime { get; set; }
        public string ExitDateTime { get; set; }
        public int UserID { get; set; }
        public int UserLogID { get; set; }
        public string IPAddres { get; set; }
        public int Expr1 { get; set; }
    }
}
